### ISSUE TITLE
Not working on Pixel 6 Pro most recent Android 13 build

### ISSUE THREAD

**Issue by DarkKronicle** [agnostic-apollo/XLogcatManager#2]
**Device:** Google Pixel 6 Pro
**Build:** Android 13 TQ2A.230305.008.E1

I'm using LSPosed and after enabling this module and rebooting the new option did not appear. From what I could tell with logcat there were no logs linked to this application.

![image](https://user-images.githubusercontent.com/38167691/230532076-8e65aadf-abc2-4887-b753-93a9315bc05f.png)

Any idea if I need to set something else up? I know LSPosed is working since I have a different module. For this one it is set for "System Framework".

**Comment by agnostic-apollo** [comment]
Can you test if `v0.2.0` works for you? Thanks.

https://github.com/agnostic-apollo/XLogcatManager/releases/tag/v0.2.0
