### ISSUE TITLE
Not working with Android 12L

### ISSUE THREAD

**Issue by varunpilankar** [agnostic-apollo/XLogcatManager#3]
Recently installed LOS 19.1 latest build, post which all my logcat entry Tasker events stopped working.

I tried installing XLogManager for Lsposed but the apk is not compatible for A12L.

**Comment by agnostic-apollo** [comment]
Android `LogcatManager` was added in Android `13`, read the README.

https://github.com/agnostic-apollo/XLogcatManager/tree/master#xlogcatmanager
